apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: coordinator-agent
spec:
  description: Host UI and coordinator that routes content creation tasks to planner/writer/editor agents.
  type: BYO
  byo:
    deployment:
      image: 10.140.0.2:5001/coordinator-agent:latest
      imagePullPolicy: IfNotPresent
      env:
        # ollama/aliyun/google
        - name: PROVIDER
          value: "google"
        - name: MODEL
          value: "gemini-2.5-flash"
        # ollama: "http://10.68.186.140:11434"
        # aliyun: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        # google: ""
        - name: API_BASE
          value: ""
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: kagent-google
              key: GOOGLE_API_KEY
        - name: ALIYUN_API_KEY
          valueFrom:
            secretKeyRef:
              name: aliyun-api-key
              key: ALIYUN_API_KEY
        - name: OLLAMA_API_KEY
          valueFrom:
            secretKeyRef:
              name: fake-ollama-secret
              key: fakeKey
