repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files # Default is 500kB

  # Ensure uv.lock file is up to date with pyproject.toml
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.27
    hooks:
      - id: uv-lock
