apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: content-planner-agent
spec:
  description: Creates outlines for content given a high-level description of the content.
  type: BYO
  byo:
    deployment:
      image: 10.140.0.2:5001/content_planner_agent:latest
      imagePullPolicy: Always
      env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: kagent-google
              key: GOOGLE_API_KEY
