# queries.py
# 存储用于 Locust 测试的示例查询

SAMPLE_QUERIES = [
    # --- 来自 README 的原始查询 ---
    "Create a LinkedIn post about getting started with the Agent2Agent protocol",
    "Create a short, upbeat series of X posts about getting started with Java",

    # --- 扩展查询 ---
    "Write a professional blog post about multi-agent collaboration",
    "Generate a technical overview of the A2A Python SDK",
    "Draft an engaging email to developers about the new A2A Java SDK",
    "Create a simple summary of what Google ADK is",
    "Write a detailed comparison between Genkit and Quarkus LangChain4j for AI agents",
    "Create a series of 3 X posts about the benefits of A2A protocol",
    "Draft a LinkedIn post announcing a new agent written in TypeScript with Genkit",
    "Summarize the key features of the A2A JavaScript SDK",
    "Write an introductory article on 'Agent-to-Agent' interoperability",
    "Create a short marketing blurb for the 'Content Planner Agent'",
    "Generate a 'getting started' guide for the 'Content Writer Agent' using Java",
    "Draft a technical post explaining how the 'Content Editor Agent' improves content",
    "Write a short, upbeat LinkedIn post about Python 3.13 and the A2A SDK",
    "Create a technical deep dive on how A2A enables language-agnostic agents",
    "Generate 5 X posts about the future of multi-agent systems",
    "Write a blog post: 'Why we chose Quarkus LangChain4j for our Java agent'",
    "Draft a LinkedIn post on the flexibility of swapping agents (e.g., JS to Java editor)",
    "Create a summary of the security disclaimer in the A2A documentation",
    "Write a 'how-to' guide on using 'uv' for Python package management in AI projects",
    "Generate a simple explanation of the 'Host Agent' orchestrator role",
    
    # --- 更多变化 (内容类型) ---
    "Create an outline for a webinar about multi-agent collaboration",
    "Draft a script for a 1-minute YouTube short about Genkit",
    "Write the FAQ section for an A2A protocol website",
    "Generate ad copy for a campaign promoting the A2A Java SDK",
    "Create a press release about the open-sourcing of the A2A SDKs",
    "Write a LinkedIn article about the 'Content Creation Standard' architecture",
    "Draft a response to a developer asking 'Why A2A?'",
    "Create a tutorial script for the Content Planner Agent",
    "Write a short, catchy X post about the A2A JavaScript SDK",
    "Generate a slide deck outline for a talk on Google ADK",

    # --- 更多变化 (主题) ---
    "Create a detailed blog post on securing A2A communications",
    "Write a LinkedIn post about the importance of input sanitization for LLM prompts",
    "Generate a 'best practices' list for building agents with Google ADK",
    "Draft an article comparing the A2A Python, Java, and JS SDKs",
    "Create a short X post about Quarkus and its use in AI",
    "Write a professional summary of the 'Disclaimer' section of the A2A README",
    "Generate a 'call for contributions' post for the A2A GitHub repos",
    "Draft a LinkedIn post thanking the Genkit community",
    "Create a technical comparison of using TypeScript vs. Java for the Content Editor Agent",
    "Write a short, upbeat post about the 'uv' packaging tool",
    
    # --- 更多变化 (风格) ---
    "Write a very simple, non-technical explanation of the A2A protocol",
    "Create an expert-level technical deep-dive on the A2A protocol's mechanics",
    "Draft a witty series of X posts about debugging multi-agent systems",
    "Generate a formal announcement for a new release of the A2A Java SDK",
    "Create a fun, engaging LinkedIn post about the 'Content Creation Swapped' architecture",
    "Write a concise summary of the 'Prerequisites' for running the demo",
    "Draft a compelling argument for using Python 3.13",
    "Generate a short, punchy X post about why interoperability matters",
    "Create a list of 5 'quick tips' for using Google ADK",
    "Write a friendly blog post about the learning curve for Genkit",

    # --- 组合 ---
    "Create a professional LinkedIn post about AI agent interoperability using A2A",
    "Write a short, upbeat series of X posts about the A2A Python SDK",
    "Generate a technical overview of the Content Editor Agent (TypeScript/Genkit)",
    "Draft an engaging blog post about the 'Content Creation' pipeline architecture",
    "Create a simple summary of what Quarkus LangChain4j does",
    "Write a detailed comparison of the A2A Java SDK and A2A JS SDK",
    "Create a series of 5 X posts about the power of Google ADK",
    "Draft a LinkedIn post explaining the role of the 'Host Agent'",
    "Summarize the key benefits of using 'uv' for Python projects",
    "Write an introductory article on multi-agent systems with Google ADK",
    "Create a short marketing blurb for the A2A protocol itself",
    "Generate a 'getting started' guide for setting up the full multi-language demo",
    "Draft a technical post about the security implications of untrusted agent input",
    "Write a short, upbeat LinkedIn post about the A2A community",
    "Create a technical deep dive on the 'Content Writer Agent' (Java/Quarkus)",
    "Generate 3 X posts about why Python 3.13 is important for the A2A SDK",
    "Write a blog post: 'Our Journey Building a Multi-Language Agent System'",
    "Draft a LinkedIn post on the flexibility demonstrated by swapping the Content Editor agents",
    "Create a summary of the 'Setup and Deployment' section from the README",
    "Write a 'how-to' guide on testing the UI at http://0.0.0.0:8083",

    # --- 更多 ---
    "Create a detailed blog post on the 'Agent2Agent (A2A) protocol'",
    "Write a short LinkedIn post about the 'Content Planner Agent' in Python",
    "Generate a series of X posts about the 'Content Writer Agent' in Java",
    "Draft an engaging article about the 'Content Editor Agent' in TypeScript and Genkit",
    "Create a simple summary of the 'Host Agent' (Python, Google ADK)",
    "Write a technical overview of the A2A Java SDK",
    "Create a LinkedIn post comparing the TypeScript and Java Content Editor agents",
    "Draft an email explaining the 'Architecture' of the content creation pipeline",
    "Generate a short, upbeat X post about the 'App UI' screenshot",
    "Write a professional blog post about 'uv' and Python 3.13 requirements",
    "Create a 'getting started' guide based on the 'Setup and Deployment' steps",
    "Draft a LinkedIn post about the 'Disclaimer' on production use",
    "Summarize the 'References' section (A2A SDKs)",
    "Write a technical post on the security warning about 'untrusted input' and 'prompt injection'",
    "Create a simple explanation of 'language-agnostic interoperability' using A2A",
    "Generate a short X post about the 'ContentCreationStandard.png' diagram",
    "Write a LinkedIn post about the 'ContentCreationSwapped.png' and its implications",
    "Draft an article: 'The Power of A2A: Swapping Agents Seamlessly'",
    "Create a 'Top 5 Features' list for the A2A Python SDK",
    "Write a short, technical X post about Quarkus LangChain4j",
    "Generate a blog post about the role of Genkit in the JS Content Editor"
]